name: project-minato

services:
  postgres:
    image: postgres
    container_name: project-minato-postgres
    environment:
      POSTGRES_DB: project-minato
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - project-minato_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  project-minato_postgres_data:
